### ISSUE TITLE
AttributeError: power not found

### ISSUE THREAD

**Issue by GianniCristian** [stanly3690/HotSpotAnalysis_Plugin#5] opened 2017-08-04 09:57 UTC
Dear All,

I'm trying to run the plugin but I got the error below. I've tried both on Ubuntu and Windows, but I still get the same error.

```
Traceback (most recent call last):
			  File "C:/Users/user/.qgis2/python/plugins\HotspotAnalysis\hotspot_analysis.py", line 603, in run
			    w = DistanceBand(t, threshold1, p=2, binary=False)
			  File "C:\OSGEO4~1\apps\Python27\lib\site-packages\pysal\weights\Distance.py", line 789, in __init__
			    neighbors, weights = self._distance_to_W(ids)
			  File "C:\OSGEO4~1\apps\Python27\lib\site-packages\pysal\weights\Distance.py", line 888, in _distance_to_W
			    weighted = self.dmat.power(self.alpha)
			  File "C:\OSGEO4~1\apps\Python27\lib\site-packages\scipy\sparse\base.py", line 499, in __getattr__
			    raise AttributeError(attr + " not found")
			AttributeError: power not found
```

Thanks!

**Comment by danioxoli** [comment] 2017-08-04 13:07
Dear Gianni,

Thank you for reporting. 
Are you using the code of this repository? I am asking because we moved the code months ago to continue the development [here](https://github.com/danioxoli/HotSpotAnalysis_Plugin).

May you try to use the latest version (which is available also from the QGIS plugin repository)?

In any case, I faced the same problem occasionally and this rises from one of the dependencies (i.e. scipy). I can give you some hints before suggesting you to remove and reinstall both the dependencies and the plugin from your system:
1) Be sure first that your data are projected in a metric reference system (the problem is in the spatial weights matrix computation, therefore this might be a possible reason).
2) Try with another dataset after closing and re-runnig QGIS. In this way you will exclude that the error is brought by the shapefile
3) Remove your scipy version and install a new one (you can find the _.whl_ of the library [here](https://pypi.anaconda.org/carlkl/simple/scipy/) and install it using pip)

Please let me know if with this it will work! 
If not, you can open an issue in the new [repository](https://github.com/danioxoli/HotSpotAnalysis_Plugin)

Best

Daniele

**Comment by GianniCristian** [comment] 2017-08-04 14:38
Thanks for your prompt reply. I've used the latest code but I had to open an issue here because I wasn't able to do it on the new repository.

I've found the error. Actually I had all the library installed, but it crashed using the Scipy '0.15.1' version. I did update on the '0.16.0' release and it worked. 

Thanks,
Gianni

**Closed as completed** 2017-09-13 07:50 UTC
